"""add language to posts

Revision ID: 635c27730f01
Revises: 6520ab80170f
Create Date: 2018-04-01 15:10:07.733291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635c27730f01'
down_revision = '6520ab80170f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###